# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
INHERIT: mkdocs/base.yml  # use the shared AutoRA configuration by default

site_name: AutoRA User Cookiecutter
repo_url: 'https://github.com/AutoResearch/autora-user-cookiecutter'

nav:
- Home: 'index.md'
