# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
INHERIT: mkdocs/base.yml  # use the shared AutoRA configuration by default

site_name: AutoRA User Cookiecutter
repo_url: 'https://github.com/AutoResearch/autora-user-cookiecutter'

nav:
- Home: 'index.md'
- Examples:
    - Mathematical Model Discover: 'examples/Mathematical Model Discovery.ipynb'


plugins:
  mkdocs-jupyter: # required to convert Jupyter notebooks
    include_source: true
    execute: false
    ignore_h1_titles: true
    ignore: [
      # ignore all files in the src/ directories – these don't need to be converted
      # this is needed because the pathlib PurePath.match doesn't allow for "**" patterns
      # (see https://github.com/python/cpython/pull/11171)
      # We don't want to just ignore all python files, because someone may at some point want to
      # use a .py notebook.
      # Alternatively, we could just have ignore: [ "*.py" ], but then we wouldn't be able to use
      #
      "src/autora/*.py",
      "src/autora/*/*.py",
      "src/autora/*/*/*.py",
      "src/autora/*/*/*/*.py",
      "src/autora/*/*/*/*/*.py",
    ]