# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
INHERIT: mkdocs/base.yml  # use the shared AutoRA configuration by default

site_name: AutoRA Model-Disagreement-Sampler
repo_url: 'https://github.com/AutoResearch/autora-experimentalist-sampler-model-disagreement-sampler'

nav:
- Initialize Firebase Project: 'initialize-firebase-project.md'